### ISSUE TITLE
Can not generate API keys with Roles

### ISSUE THREAD

**Issue by juergenthomann** [shlinkio/shlink#1590]
#### How Shlink is set-up

* Shlink Version: 3.3.2
* PHP Version: 8.1
* How do you serve Shlink: Docker image
* Database engine used: PostgreSQL 14

#### Summary

I would like to create a domain specific API Key but I always get an exception

#### Current behavior

```
bin/cli api-key:generate --domain-only=example.com

Fatal error: Uncaught Error: Object of class Shlinkio\Shlink\Rest\ApiKey\Role could not be converted to string in /etc/shlink/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:56
Stack trace:
#0 /etc/shlink/vendor/doctrine/dbal/src/Driver/PDO/Statement.php(56): PDOStatement->bindValue(1, Object(Shlinkio\Shlink\Rest\ApiKey\Role), 2)
#1 /etc/shlink/vendor/doctrine/dbal/src/Statement.php(115): Doctrine\DBAL\Driver\PDO\Statement->bindValue(1, Object(Shlinkio\Shlink\Rest\ApiKey\Role), 2)
#2 /etc/shlink/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(274): Doctrine\DBAL\Statement->bindValue(1, Object(Shlinkio\Shlink\Rest\ApiKey\Role), Object(Doctrine\DBAL\Types\StringType))
#3 /etc/shlink/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1129): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /etc/shlink/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(430): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /etc/shlink/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(403): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /etc/shlink/vendor/doctrine/orm/lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php(211): Doctrine\ORM\EntityManager->flush(NULL)
#7 /etc/shlink/module/Rest/src/Service/ApiKeyService.php(33): Doctrine\ORM\Decorator\EntityManagerDecorator->flush()
#8 /etc/shlink/module/CLI/src/Command/Api/GenerateKeyCommand.php(96): Shlinkio\Shlink\Rest\Service\ApiKeyService->create(NULL, NULL, Object(Shlinkio\Shlink\Rest\ApiKey\Model\RoleDefinition))
#9 /etc/shlink/vendor/symfony/console/Command/Command.php(308): Shlinkio\Shlink\CLI\Command\Api\GenerateKeyCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /etc/shlink/vendor/symfony/console/Application.php(1002): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /etc/shlink/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Shlinkio\Shlink\CLI\Command\Api\GenerateKeyCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /etc/shlink/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /etc/shlink/bin/cli(10): Symfony\Component\Console\Application->run()
#14 {main}
  thrown in /etc/shlink/vendor/doctrine/dbal/src/Driver/PDO/Statement.php on line 56
```

My guess would be that doctrine has problems with converting the enum to a string field in the database. Creating keys without a role works without any problems.

If you would like to have some debug statements at some place, let me know and I'll try them.

Thank you

**Comment by acelaya** [comment]
I think it's not doctrine's fault but an actual bug. I believe I fixed it already in latest.

Could you try if this is reproducible with `latest` docker tag?

If it's not, then I know the reason and it should be easy to backport.

**Comment by juergenthomann** [comment]
I tried it with latest and still fails. I also only have that problem in 1 Instance and another instance works without problems...

**Comment by acelaya** [comment]
That could mean you actually don't have the "latest" `latest` on one of the instances (the one failing, probably).

Could you try running `docker pull` on that image first?

**Comment by juergenthomann** [comment]
I confirmed so far that I am using the latest image.
Somehow I get a different image with docker pull on latest than docker hub tells me, but I tried it now with @sha256:c327bdedb50330aebd94bc56ffc5c7f31b6ef74ba6faee1098ae6628acbd7245 (docker hub hash) and @sha256:d29018d3fc4f3f71c8e1c255fbdacef702212f3463a132601d1a28b58f585cd9 what I get when I do a docker pull and they both seems to be the same when I do a docker image inspect.

**Comment by acelaya** [comment]
Have you managed to pull the latest one? Maybe you can try with `3.4.0` or `stable` now. They both include the fix for the originally reported error.

**Comment by juergenthomann** [comment]
Sorry for the late answer, vacation...
Can confirm that it is now working with the new version. Thank you
